bump github actions
joggrdocs/fastify-prisma pull request #7
Opened 2023-09-18 18:08 UTC by Fdawgs

### Description

This PR bumps GitHub Actions to their latest major versions, which now use Node 16 internally instead of Node 12 (EOL as of end of April 2022, no longer receives security updates)

### References
- Changelog for `actions/checkout` can be [found here](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- Releases for `actions/setup-node` can be [found here](https://github.com/actions/setup-node/releases)

### Testing

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in Slab
- [ ] I have updated or added public documentation
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `main`

2023-09-18 18:13 UTC, Fdawgs commented
There's probably a few more things that could be done to beef up CI security:
-   Declares the minimum permissions for CI workflows to run at the workflow level, following principle of least privilege; see [related GitHub security post](https://securitylab.github.com/research/github-actions-building-blocks/)
-   Removes Git credentials/SSH keys after checkout as a security precaution by setting `persist-credentials` to false for `actions/checkout` action

2023-09-18 18:23 UTC, zrosenbauer commented
@Fdawgs good looking on the updating the actions, bad C+P on our end 😄 

I'll take a look at the permissions.

On the `npm install` that was intentional as the prismaclient is a peer dep, we have to rely on the installers dep due to prisma nesting the client in the `.prisma` dir unless I'm misunderstanding how prisma generates its client.

2023-09-18 21:43 UTC, zrosenbauer commented
@Fdawgs looks like its still failing (no idea why tbh) also made changes to deploy process so might conflict

I'm happy to merge just the updates to the GHA actions and do the `npm` changes in diff PR?

2023-09-19 17:18 UTC, zrosenbauer commented on .github/workflows/ci.yaml
> +        run: npm i
This seems to work solves the `Module '"@prisma/client"' has no exported member 'PrismaClient'` error.

It looks like this is probably "fixing" it => https://github.com/prisma/prisma/blob/f718439571a60c91d3f5440226fe71031c84fa58/packages/client/package.json#L48

Maybe we `npm i @prisma/client & npx prisma generate`  and `npm i --ignore-scripts`?

Its only getting hit on the typecheck...

2023-09-19 17:19 UTC, zrosenbauer requested changes
Until we can figure out the `npm i` I don't want to merge, we can merge in the GHA upgrades though

2023-09-19 18:56 UTC, Fdawgs commented
> @Fdawgs looks like its still failing (no idea why tbh) also made changes to deploy process so might conflict
> 
> I'm happy to merge just the updates to the GHA actions and do the `npm` changes in diff PR?

sounds good, will update PR.

2023-09-19 22:45 UTC, zrosenbauer approved these changes

2023-09-19 22:45 UTC, merged